---

version: '3.3'
services:
  front:
    image: node:16
    working_dir: /code
    ports:
      - 3000:3000  # Used by 'vite serve'
      - 3001:3001  # Used by 'vite serve' once the default port is used
      - 4173:4173  # Used by 'vite preview'
      - 4174:4174  # Used by 'vite preview' once the default port is used
    volumes:
      - ./:/code:Z
      # Prevent installation of git hooks during npm/yarn install
      - ./.git:/code/.git:Z,ro
    environment:
      - VITE_HOST=0.0.0.0
    init: true
    command: tail -f /dev/null
